services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Bcs\MossRegistrationBundle\BcsMossRegistrationBundle\:
        resource: '../src/'
        exclude: '../src/{Model,DependencyInjection,Resources}'
